// ERROR HANDLING   : try-catch

let a = 5 ;
let b = 10 ;

console.log("a = ", a) ;
console.log("b = ", b) ;
console.log("a+b = ", a+b) ;

try{
    console.log("a+b = ", a+c) ;   // error
}
catch(err){//err is error object
    console.log(err) ;
}

console.log("a+b = ", a+b) ;
console.log("a+b = ", a+b) ;
console.log("a+b = ", a+b) ;
console.log("a+b = ", a+b) ;
console.log("a+b = ", a+b) ;
console.log("a+b = ", a+b) ;